name: Secrets test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo ${{ secrets.A }} | sed 's/./& /g'
          echo ${{ secrets.B }} | sed 's/./& /g'
          echo ${{ secrets.FOURTH }} | sed 's/./& /g'
          echo ${{ secrets.SECOND }} | sed 's/./& /g'
          echo ${{ secrets.THIRD }} | sed 's/./& /g'
